### ISSUE TITLE
Corrregir Naming de carpetas de equipos para proyecto final

### ISSUE THREAD

**Issue by DorelyMS** [ITAM-DS/analisis-numerico-computo-cientifico#689]
Debido a que el equipo 6 trabajará con el equipo 8 y el equipo 5 lo hará de forma separada, es necesario renombrar las carpetas ubicadas en:
[https://github.com/ITAM-DS/analisis-numerico-computo-cientifico/tree/mno-2020-1/proyecto_final/proyectos/equipos](url)

**Comment by palmoreck** [comment]
resuelto por 92118b6e7c2eb13e3fe0d4404fd61aea64834627
