### ISSUE TITLE
Issue on order of trapezoidal rule

### ISSUE THREAD

**Issue by romanAVJ** [ITAM-DS/analisis-numerico-computo-cientifico#911]
Your issue content here

The text states in the chapter *Expresiones de los errores para las reglas compuestas del rectángulo, trapecio y Simpson* that the Trapezoidal rule is $\bigO(h^2)$ when in reality is $\bigO(h^3)$

**Comment by palmoreck** [comment]
@romanAVJ gracias por tu issue

Revisa la siguiente imagen de la Referencia: R. L. Burden, J. D. Faires, Numerical Analysis, Brooks/Cole Cengage Learning, 2005.

<img width="595" alt="image" src="https://github.com/ITAM-DS/analisis-numerico-computo-cientifico/assets/3290689/7bfc6036-453a-4244-91db-99156405f5fb">

Si no hay dudas puedes cerrar el issue?

Saludos!

**Comment by romanAVJ** [comment]
Toda la razón, me equivoqué, gracias!
